[package]
name = "re_transport"
authors.workspace = true
description = "Helpers for encoding and transporting Rerun log messages"
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true


[features]


[dependencies]

# Rerun:
re_log.workspace = true
re_log_types.workspace = true
re_smart_channel.workspace = true

# External:
ehttp = "0.2"


# Web dependencies:
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
